import type { Metadata } from "next";
import { Geist, Geist_Mono, Antonio, League_Spartan } from "next/font/google";
import "./globals.css";
import { PlanetProvider } from "../context/PlanetContext";

const spartanFont = League_Spartan({
  variable: "--font-spartan",
  subsets: ["latin"],
});

const antonioFont = Antonio({
  variable: "--font-antonio",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${spartanFont.variable}  ${antonioFont.variable} ${geistMono.variable} antialiased`}
      >
        <PlanetProvider>{children}</PlanetProvider>
      </body>
    </html>
  );
}
